import Head from 'next/head'
import Image from 'next/image'
import Widget from '../components/Widget'

export default function Home() {
  const languages = [
    'Python',
    'Java',
    'Javascript',
    'C#',
    'C/C++',
    'PHP',
    'R',
    'Objective-C',
    'Swift',
    'Typescript',
    'Golang',
    'Ruby',
    'Bash',
    'Kotlin',
    'jQuery',
    'Lisp',
    'ML',
    'MySQL',
    'XML'
  ]
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Widget languages={languages} />
      </main>
    </div>
  )
}
